# Help: rename the adject docker-compose.override.example.yml file to docker-compose.override.yml
#       then in the override file uncomment the environment tag for the collectors you want to
#       run. Then add the environment vars you want to use.
version: '3'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "db-data:/data/db"

  db-setup:
    build: db
    depends_on:
      - db

  ui:
    build: UI
    image: hygieia-ui
    depends_on:
      - api
    ports:
      - "3000:80"

volumes:
  db-data:
  certs:
