version: '3'
services:

  api-audit:
    # environment:

  ui:
    # environment:

  appdynamics-collector:
    # environment:

  artifactory-artifact-collector:
    # environment:

  bamboo-build-collector:
    # environment:

  chat-ops-collector:
    # environment:

  hpsm-cmdb-collector:
    # environment:

  github-graphql-collector:
    # environment:

  gitlab-feature-collector:
    # environment:

  gitlab-scm-collector:
    # environment:

  jenkins-build-collector:
    # environment:

  jenkins-codequality-collector:
    # environment:

  jenkins-cucumber-test-collector:
    # environment:

  jira-collector:
    # environment:

  nexus-iq-collector:
    # environment:

  udeploy-collector:
    # environment:

  versionone-collector:
    # environment:

  xldeploy-collector:
    # environment:
